export interface IMIME{
  "audio/x-mpeg": string
  "application/postscript": string
  "audio/x-aiff": string
  "application/x-aim": string
  "image/x-jg": string
  "video/x-ms-asf": string
  "audio/basic": string
  "video/x-msvideo": string
  "video/x-rad-screenplay": string
  "application/x-bcpio": string
  "application/octet-stream": string
  "image/bmp": string
  "text/html": string
  "application/x-cdf": string
  "application/pkix-cert": string
  "application/java": string
  "application/x-cpio": string
  "application/x-csh": string
  "text/css": string
  "application/msword": string
  "application/xml-dtd": string
  "video/x-dv": string
  "application/x-dvi": string
  "application/vnd.ms-fontobject": string
  "text/x-setext": string
  "image/gif": string
  "application/x-gtar": string
  "application/x-gzip": string
  "application/x-hdf": string
  "application/mac-binhex40": string
  "text/x-component": string
  "image/ief": string
  "text/vnd.sun.j2me.app-descriptor": string
  "application/java-archive": string
  "text/x-java-source": string
  "application/x-java-jnlp-file": string
  "image/jpeg": string
  "application/javascript": string
  "text/plain": string
  "application/json": string
  "audio/midi": string
  "application/x-latex": string
  "audio/x-mpegurl": string
  "image/x-macpaint": string
  "text/troff": string
  "application/mathml+xml": string
  "application/x-mif": string
  "video/quicktime": string
  "video/x-sgi-movie": string
  "audio/mpeg": string
  "video/mp4": string
  "video/mpeg": string
  "video/mpeg2": string
  "application/x-wais-source": string
  "application/x-netcdf": string
  "application/oda": string
  "application/vnd.oasis.opendocument.database": string
  "application/vnd.oasis.opendocument.chart": string
  "application/vnd.oasis.opendocument.formula": string
  "application/vnd.oasis.opendocument.graphics": string
  "application/vnd.oasis.opendocument.image": string
  "application/vnd.oasis.opendocument.text-master": string
  "application/vnd.oasis.opendocument.presentation": string
  "application/vnd.oasis.opendocument.spreadsheet": string
  "application/vnd.oasis.opendocument.text": string
  "application/vnd.oasis.opendocument.graphics-template": string
  "application/vnd.oasis.opendocument.text-web": string
  "application/vnd.oasis.opendocument.presentation-template": string
  "application/vnd.oasis.opendocument.spreadsheet-template": string
  "application/vnd.oasis.opendocument.text-template": string
  "application/ogg": string
  "video/ogg": string
  "audio/ogg": string
  "application/x-font-opentype": string
  "audio/flac": string
  "application/annodex": string
  "audio/annodex": string
  "video/annodex": string
  "application/xspf+xml": string
  "image/x-portable-bitmap": string
  "image/pict": string
  "application/pdf": string
  "image/x-portable-graymap": string
  "audio/x-scpls": string
  "image/png": string
  "image/x-portable-anymap": string
  "image/x-portable-pixmap": string
  "application/vnd.ms-powerpoint": string
  "image/vnd.adobe.photoshop": string
  "image/x-quicktime": string
  "image/x-cmu-raster": string
  "application/rdf+xml": string
  "image/x-rgb": string
  "application/vnd.rn-realmedia": string
  "application/rtf": string
  "text/richtext": string
  "application/font-sfnt": string
  "application/x-sh": string
  "application/x-shar": string
  "application/x-stuffit": string
  "application/x-sv4cpio": string
  "application/x-sv4crc": string
  "image/svg+xml": string
  "application/x-shockwave-flash": string
  "application/x-tar": string
  "application/x-tcl": string
  "application/x-tex": string
  "application/x-texinfo": string
  "image/tiff": string
  "text/tab-separated-values": string
  "application/x-font-ttf": string
  "application/x-ustar": string
  "application/voicexml+xml": string
  "image/x-xbitmap": string
  "application/xhtml+xml": string
  "application/vnd.ms-excel": string
  "application/xml": string
  "image/x-xpixmap": string
  "application/xslt+xml": string
  "application/vnd.mozilla.xul+xml": string
  "image/x-xwindowdump": string
  "application/vnd.visio": string
  "audio/x-wav": string
  "image/vnd.wap.wbmp": string
  "text/vnd.wap.wml": string
  "application/vnd.wap.wmlc": string
  "text/vnd.wap.wmlsc": string
  "application/vnd.wap.wmlscriptc": string
  "video/x-ms-wmv": string
  "application/font-woff": string
  "application/font-woff2": string
  "model/vrml": string
  "application/wspolicy+xml": string
  "application/x-compress": string
  "application/zip": string
}

export interface IExtention{
  mpega: string
  ps: string
  aiff: string
  aim: string
  art: string
  asx: string
  ulw: string
  avi: string
  avx: string
  bcpio: string
  exe: string
  dib: string
  html: string
  cdf: string
  cer: string
  class: string
  cpio: string
  csh: string
  css: string
  doc: string
  dtd: string
  dv: string
  dvi: string
  eot: string
  etx: string
  gif: string
  gtar: string
  gz: string
  hdf: string
  hqx: string
  htc: string
  ief: string
  jad: string
  jar: string
  java: string
  jnlp: string
  jpg: string
  js: string
  txt: string
  json: string
  midi: string
  latex: string
  m3u: string
  pnt: string
  tr: string
  mathml: string
  mif: string
  qt: string
  movie: string
  mpa: string
  mp4: string
  mpg: string
  mpv2: string
  src: string
  nc: string
  oda: string
  odb: string
  odc: string
  odf: string
  odg: string
  odi: string
  odm: string
  odp: string
  ods: string
  odt: string
  otg: string
  oth: string
  otp: string
  ots: string
  ott: string
  ogx: string
  ogv: string
  spx: string
  otf: string
  flac: string
  anx: string
  axa: string
  axv: string
  xspf: string
  pbm: string
  pict: string
  pdf: string
  pgm: string
  pls: string
  png: string
  pnm: string
  ppm: string
  pps: string
  psd: string
  qtif: string
  ras: string
  rdf: string
  rgb: string
  rm: string
  rtf: string
  rtx: string
  sfnt: string
  sh: string
  shar: string
  sit: string
  sv4cpio: string
  sv4crc: string
  svgz: string
  swf: string
  tar: string
  tcl: string
  tex: string
  texinfo: string
  tiff: string
  tsv: string
  ttf: string
  ustar: string
  vxml: string
  xbm: string
  xhtml: string
  xls: string
  xsl: string
  xpm: string
  xslt: string
  xul: string
  xwd: string
  vsd: string
  wav: string
  wbmp: string
  wml: string
  wmlc: string
  wmls: string
  wmlscriptc: string
  wmv: string
  woff: string
  woff2: string
  wrl: string
  wspolicy: string
  z: string
  zip: string
}
